languageCode = "en"
languageName = "English"
weight = 1
title = "Madhusudan"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  secondaryLogo = "img/logo.png"
  description = "ICT Systems and Infrastructure Professional"
  # copyright = "Madhusudan"

 [author]
   name = "MADHUSUDAN UPADHYAY"
   image = "img/logo.png"
   headline = "ICT Systems and Infrastructure Professional"
#   bio = "ICT Systems and Infrastructure Professional"
links = [
    { x-twitter = "https://twitter.com/meupadhyay" },
    { linkedin = "https://www.linkedin.com/in/madhusudanupadhyay/" },
    { email = "mailto:email@Madhusudanupadhyay.com.np" },
  ]
